### PR TITLE
New features 

### PR DESCRIPTION
**Pull request by eren-ck**
- Updated to d3 v5 
- Zoom and pan the spectrogram 
- Play, pause and stop the animation and audio 
- Binning to improve the draw performance of the spectrogram for bigger files 
- Custom color schemes 
- Removed jQuery dependency 
- Updated readme

### CODE REVIEW

**Comment by vlandham** [comment]
wow! what an overhaul!

Love the new zoom and color scheme options. And the spinner is very nice as well!
Thanks so much for modernizing and cleaning up all this old code - it was certainly written at a time where i knew even less about JS than i do now - and it shows!

I'll merge this and add an update to the original post to indicate all these great changes - in case anyone reads that again.

Thanks again!!!!

**Comment by eren-ck** [comment]
Hi, 

I am happy that the new functionalities work so far. 
Would you mind adding a license to the repository? That would be cool.  Maybe something like the Apache License 2.0. This would be nice for future new features and changes to the library. 

Cheers, 
Eren

**Comment by vlandham** [comment]
certainly. would you prefer Apache 2.0 over the MIT License? I've used MIT in the past - but don't have a strong opinion. ... 

https://exygy.com/which-license-should-i-use-mit-vs-apache-vs-gpl/

**Comment by eren-ck** [comment]
Sure, MIT License is also fine.

**Comment by vlandham** [comment]
done! https://github.com/vlandham/spectrogramJS/pull/3

**Pull request merged**
